shareandcare/account/urls.py
from django.conf import settings
from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('login', views.login_view, name='login'),
    path('signup', views.signup_view, name='signup'),
    path('logout', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit', views.edit_profile_view, name='edit_profile'),
    path('profile/password&update', views.update_password_view, name='update_password'),
]

shareandcare/foodpost/urls.py
from django.conf import settings
from django.urls import path

from . import views

app_name = 'foodpost'
urlpatterns = [
    path('my-posts', views.my_post_view, name='mypost'),
    path('add-posts', views.add_post_view, name='addpost'),
    path('my-posts/<int:post_id>', views.my_post_detail_view, name='myPostDetail'),
    path('my-posts/<int:post_id>/edit', views.edit_post_view, name='editPost'),
    path('my-posts/<int:post_id>/delete', views.delete_post_view, name='deletePost'),
]

shareandcare/homepage/urls.py
from django.conf import settings
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('<username>', views.home_page_view, name='home'),
    path('post/<int:post_id>', views.home_page_post_view, name='homePostView'),
]

shareandcare/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shareandcare.account.urls', namespace='account')),
    path('home/', include('shareandcare.homepage.urls', namespace='homepage')),
    path('', include('shareandcare.foodpost.urls', namespace='foodpost')),
]

shareandcare/homepage/models.py
from django.db import models

shareandcare/homepage/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render

from shareandcare.foodpost import models

from .filters import PostFilter


@login_required(login_url='account:login')
def home_page_view(request, username):
    user = get_object_or_404(User, username=username)
    all_posts = models.FoodPost.objects.exclude(user=request.user.id)
    args = {
        'username': user,
        'filter_posts': PostFilter(request.GET, queryset=all_posts),
    }
    return render(request, 'homepage/homepage.html', args)

@login_required(login_url='account:login')
def home_page_post_view(request, post_id):
    args = {
        'username': request.user,
        'post': models.FoodPost.objects.get(id=post_id),
    }
    return render(request, 'homepage/homepage_posts.html', args)

shareandcare/homepage/templates/homepage/homepage.html
{% extends 'base.html' %}

{% block title %}ShareAndCare - Home{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'homepage:home' username %}">ShareAndCare</a>
    </div>
  </div>
  <div class="dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
      aria-expanded="false">More Menu</a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
    </div>
  </div>
</nav>
<div class="container">
  <br />
  <form method="GET">
    {{ filter_posts.form.as_p }}
    <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
  </form>
  <br />
  <a href="{% url 'foodpost:addpost' %}"><button class="btn btn-primary my-2 my-sm-0">New Post</button></a>
  <br />
  <br />
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'homepage:home' username %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'foodpost:mypost' %}">My Posts</a>
    </li>
  </ul>
  <table class="table table-hover">
    <thead>
      <th scope="col">Posts</th>
    </thead>
    <tbody>
      <tr>
        <td>
          {% for post in filter_posts.qs %}
          <ul>
            <a class="btn btn-link" href="{% url 'homepage:homePostView' post.id %}">{{ post.title }}</a>
          </ul>
          {% endfor %}
        </td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

shareandcare/homepage/templates/homepage/homepage_posts.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'homepage:home' username %}">ShareAndCare</a>
    </div>
  </div>
  <div class="dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
      aria-expanded="false">More Menu</a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
    </div>
  </div>
</nav>
<div class="container">
  <h5>Title: {{ post.title }}</h5>
  <h5>Posted by: {{ post.user.first_name }} {{ post.user.last_name }}</h5>
  <h5>Description: {{ post.description }}</h5>
  <h5>Date published: {{ post.publishing_date }}</h5>
  <h5>Country: {{ post.country }}</h5>
  <h5>City: {{ post.city }}</h5>
  <h5>Address: {{ post.address }}</h5>
</div>
{% endblock %}