shareandcare/account/urls.py
from django.conf import settings
from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('login', views.login_view, name='login'),
    path('signup', views.signup_view, name='signup'),
    path('logout', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit', views.edit_profile_view, name='edit_profile'),
    path('profile/password&update', views.update_password_view, name='update_password'),
]

shareandcare/foodpost/urls.py
from django.conf import settings
from django.urls import path

from . import views

app_name = 'foodpost'
urlpatterns = [
    path('my-posts', views.my_post_view, name='mypost'),
    path('add-posts', views.add_post_view, name='addpost'),
    path('my-posts/<int:post_id>', views.my_post_detail_view, name='myPostDetail'),
    path('my-posts/<int:post_id>/edit', views.edit_post_view, name='editPost'),
    path('my-posts/<int:post_id>/delete', views.delete_post_view, name='deletePost'),
]

shareandcare/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shareandcare.account.urls', namespace='account')),
    path('home/', include('shareandcare.homepage.urls', namespace='homepage')),
    path('', include('shareandcare.foodpost.urls', namespace='foodpost')),
]

shareandcare/foodpost/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django_countries.fields import CountryField


class FoodPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=60, default='Excess food')
    description = models.CharField(max_length=200, default='')
    publishing_date = models.DateTimeField(default=timezone.now, blank=True)
    country = CountryField()
    city = models.CharField(max_length=30, default='')
    address = models.CharField(max_length=300, default='')

    def __str__(self):
        return f"{self.user} - {self.title}"

shareandcare/foodpost/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from . import models


class FoodPostForm(forms.ModelForm):
    title = forms.CharField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Excess food by default',
            'style': 'border-radius: 4px;',
        }
    ), )
    description = forms.CharField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'description...',
            'style': 'border-radius: 4px;',
        }
    ), )
    country = CountryField().formfield(
        widget=CountrySelectWidget(
            attrs={
                'class': 'form-control',
            }
        )
    )
    city = forms.CharField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'City...',
            'style': 'border-radius: 4px;',
        }
    ), )
    address = forms.CharField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Address...',
            'style': 'border-radius: 4px;',
        }
    ), )

    class Meta:
        model = models.FoodPost
        fields = [
            'title', 'description', 'country', 'city', 'address',
        ]

    def clean(self, *args, **kwargs):
        title = self.cleaned_data.get('title')
        description = self.cleaned_data.get('description')
        country = self.cleaned_data.get('country')
        city = self.cleaned_data.get('city')
        address = self.cleaned_data.get('address')
        return super(FoodPostForm, self).clean(*args, **kwargs)


class EditFoodPostForm(forms.ModelForm):
    title = forms.CharField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Excess food by default',
            'style': 'border-radius: 4px;',
        }
    ), )
    description = forms.CharField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'description...',
            'style': 'border-radius: 4px;',
        }
    ), )
    country = CountryField().formfield(
        widget=CountrySelectWidget(
            attrs={
                'class': 'form-control',
            }
        )
    )
    city = forms.CharField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'City...',
            'style': 'border-radius: 4px;',
        }
    ), )
    address = forms.CharField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Address...',
            'style': 'border-radius: 4px;',
        }
    ), )

    class Meta:
        model = models.FoodPost
        fields = [
            'title', 'description', 'country', 'city', 'address',
        ]

    def clean(self, *args, **kwargs):
        title = self.cleaned_data.get('title')
        description = self.cleaned_data.get('description')
        country = self.cleaned_data.get('country')
        city = self.cleaned_data.get('city')
        address = self.cleaned_data.get('address')
        return super(EditFoodPostForm, self).clean(*args, **kwargs)

shareandcare/foodpost/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from shareandcare.foodpost import forms
from shareandcare.foodpost import models

@login_required(login_url='account:login')
def my_post_view(request):
    args = {
        'my_posts': models.FoodPost.objects.filter(user=request.user.id),
        'username': request.user
    }
    return render(request, 'foodpost/my_posts.html', args)

@login_required(login_url='account:login')
def add_post_view(request):
    form = forms.FoodPostForm(request.POST or None)
    if form.is_valid():
        title = form.cleaned_data.get('title')
        description = form.cleaned_data.get('description')
        country = form.cleaned_data.get('country')
        city = form.cleaned_data.get('city')
        address = form.cleaned_data.get('address')
        new_post = models.FoodPost(user=request.user, title=title, description=description, country=country, city=city, address=address)
        new_post.save()
        # form.save()
        return redirect('foodpost:mypost')
    args = {
        'form': form,
        'username': request.user
    }
    return render(request, 'foodpost/add_post.html', args)

@login_required(login_url='account:login')
def edit_post_view(request, post_id):
    post = models.FoodPost.objects.get(id=post_id)
    form = forms.EditFoodPostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('foodpost:mypost')

@login_required(login_url='account:login')
def delete_post_view(request, post_id):
    post = models.FoodPost.objects.get(id=post_id)
    post.delete()
    return redirect('foodpost:mypost')

@login_required(login_url='account:login')
def my_post_detail_view(request, post_id):
    post = models.FoodPost.objects.get(id=post_id)
    form = forms.EditFoodPostForm(request.POST or None, instance=post)
    args = {
        'form': form,
        'username': request.user,
        'post': post,
    }
    return render(request, 'foodpost/my_posts_detail.html', args)

shareandcare/foodpost/templates/foodpost/add_post.html
{% extends 'base.html' %}

{% block title %}Add post{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'homepage:home' username %}">ShareAndCare</a>
    </div>
  </div>
  <div class="dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
      aria-expanded="false">More Menu</a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
    </div>
  </div>
</nav>
<div class="container">
  <form class="form" action="{% url 'foodpost:addpost' %}" method="POST">
    {% csrf_token %}
    <h1>Add new post</h1>
    <div class="form-group">
      <label>Title:</label>
      {{ form.title }}
    </div>
    <div class="form-group">
      <label>Description:</label>
      {{ form.description }}
    </div>
    <div class="form-group">
      <label>Country:</label>
      {{ form.country }}
    </div>
    <div class="form-group">
      <label>City:</label>
      {{ form.city }}
    </div>
    <div class="form-group">
      <label>Address:</label>
      {{ form.address }}
    </div>
    <br>
    <button type="submit" class="btn btn-primary btn-lg btn-block">Create post</button>
  </form>
</div>
{% endblock %}

shareandcare/foodpost/templates/foodpost/delete_confirm_modal.html
<!--Delete button will redirect to the href of the element with 'id = caller-id' property in this modal-->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" caller-id="" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body confirm-delete">
        This action is permanent!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="confirmDeleteButtonModal">Delete</button>
      </div>
    </div>
  </div>
</div>

shareandcare/foodpost/templates/foodpost/my_posts.html
{% extends 'base.html' %}

{% block title %}Your Posts{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'homepage:home' username %}">ShareAndCare</a>
    </div>
  </div>
  <div class="dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
      aria-expanded="false">More Menu</a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
    </div>
  </div>
</nav>
<br />
<div class="container">
  <a href="{% url 'foodpost:addpost' %}"><button class="btn btn-primary my-2 my-sm-0">New Post</button></a>
  <br />
  <br />
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'homepage:home' username %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'foodpost:mypost' %}">My Posts</a>
    </li>
  </ul>
  <table class="table table-hover">
    <thead>
      <th scope="col">Your posts</th>
    </thead>
    <tbody>
      <tr>
        <td>
          {% for post in my_posts %}
          <ul>
            <a class="btn btn-link" href="{% url 'foodpost:myPostDetail' post.id %}">{{ post.title }}</a>
          </ul>
          {% endfor %}
        </td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

shareandcare/foodpost/templates/foodpost/my_posts_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Post{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'homepage:home' username %}">ShareAndCare</a>
    </div>
  </div>
  <div class="dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
      aria-expanded="false">More Menu</a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
    </div>
  </div>
</nav>
<br />
<div class="container">
  <form action="{% url 'foodpost:deletePost' post.id %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'foodpost:deletePost' post.id %}" class="confirm-delete" data-toggle="modal"
      data-target="#confirmDeleteModal" id="deleteButton{{post.id}}"><button class="btn btn-primary my-2 my-sm-0">Delete
        Post</button></a>
  </form>
  <br />
  <form class="form" action="{% url 'foodpost:editPost' post.id %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label>Title:</label>
      {{ form.title }}
    </div>
    <div class="form-group">
      <label>Description:</label>
      {{ form.description }}
    </div>
    <div class="form-group">
      <label>Country:</label>
      {{ form.country }}
    </div>
    <div class="form-group">
      <label>City:</label>
      {{ form.city }}
    </div>
    <div class="form-group">
      <label>Address:</label>
      {{ form.address }}
    </div>
    <br>
    <button type="submit" class="btn btn-primary btn-lg btn-block">Edit post</button>
  </form>
</div>
{% include 'foodpost/delete_confirm_modal.html' %}
{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{% static 'foodpost/js/confirm_delete.js' %}"></script>
{% endblock %}